Route101_Text_16D10E:: @ 816D10E
	.string "H-help me!$"

Route101_Text_16D119:: @ 816D119
	.string "Hello! You over there!\n"
	.string "Please! Help!\p"
	.string "In my BAG!\n"
	.string "There's a POKE BALL!$"

Route101_Text_16D15E:: @ 816D15E
	.string "Wh-Where are you going?!\n"
	.string "Don't leave me like this!$"

Route101_Text_16D191:: @ 816D191
	.string "PROF. BIRCH: Whew...\p"
	.string "I was in the tall grass checking on\n"
	.string "a special POKEMON partner when I was\l"
	.string "jumped.\p"
	.string "You saved me.\n"
	.string "Thanks a lot!\p"
	.string "Oh?\p"
	.string "Hi, you're {PLAYER}{KUN}!\p"
	.string "This is not the place to chat, so come\n"
	.string "by my POKEMON LAB later, okay?$"

Route101_Text_16D25E:: @ 816D25E
	.string "If POKEMON get tired, take them to\n"
	.string "a POKEMON CENTER.\p"
	.string "There's a POKEMON CENTER in OLDALE\n"
	.string "TOWN right close by.$"

Route101_Text_16D2CB:: @ 816D2CB
	.string "Wild POKEMON will jump out at you in\n"
	.string "tall grass.\p"
	.string "If you want to catch POKEMON, you have\n"
	.string "to go into the tall grass and search.$"

Route101_Text_16D349:: @ 816D349
	.string "ROUTE 101\n"
	.string "{0x79} OLDALE TOWN$"
