RivalsHouse_2F_Text_MayGettingReady:: @ 817337E
	.string "POKEMON fully restored!\n"
	.string "Items ready, and... Huh?$"

RivalsHouse_2F_Text_MayWhoAreYou:: @ 81733AF
	.string "Huh?\n"
	.string "Who... Who are you?\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Oh, you're {PLAYER}{KUN}.\n"
	.string "So your move was today.\p"
	.string "Um... I'm MAY.\n"
	.string "Glad to meet you!\p"
	.string "I have this dream of becoming friends\n"
	.string "with POKEMON all over the world.\p"
	.string "Oh, no! I forgot!\p"
	.string "I was supposed to go help Dad catch\n"
	.string "some wild POKEMON!\p"
	.string "{PLAYER}{KUN}, I'll catch you later!$"

RivalsHouse_2F_Text_BrendanGettingReady:: @ 81735C9
	.string "Checklist: POKEMON restored...\n"
	.string "Supplies packed...\l"
	.string "Birthday errand almost ready...$"

RivalsHouse_2F_Text_BrendanWhoAreYou:: @ 81735FC
	.string "Hey!\n"
	.string "You must be {PLAYER}!\p"
	.string "You moved in next door today, right?\n"
	.string "I'm BRENDAN.\p"
	.string "Dad, PROF. BIRCH, told me you were\n"
	.string "coming.\p"
	.string "He asked me to help with something\n"
	.string "special, but I can't say too much.\p"
	.string "Do you have a POKEMON yet?\p"
	.string "No? Then you should stop by Dad's LAB\n"
	.string "when you can.\p"
	.string "Aw, wait! I'm supposed to meet Dad\n"
	.string "for fieldwork right now.\p"
	.string "Some other time, okay?$"

RivalsHouse_2F_Text_MayJustCheckingMyPokedex:: @ 81737AE
	.string "MAY: {PLAYER}{KUN}!\p"
	.string "I was just checking my POKEDEX.\p"
	.string "There's still a lot of POKEMON that\n"
	.string "I've seen but haven't caught.\p"
	.string "I wonder where I should go catch\n"
	.string "some POKEMON next?$"

RivalsHouse_2F_Text_MayWhereShouldIGoNext:: @ 8173883
	.string "MAY: I wonder where I should go catch\n"
	.string "some POKEMON next?\p"
	.string "Wouldn't it be funny if we ran into each\n"
	.string "other, {PLAYER}{KUN}?$"

RivalsHouse_2F_Text_BrendanJustCheckingMyPokedex:: @ 81738F2
	.string "BRENDAN: Hey, it's {PLAYER}.\p"
	.string "I was just checking out my POKEDEX.\p"
	.string "There are still many POKEMON that\n"
	.string "I need to catch.\p"
	.string "Checking this POKEDEX out gives me\n"
	.string "the urge to hit the road again.$"

RivalsHouse_2F_Text_BrendanWhereShouldIGoNext:: @ 81739CC
	.string "BRENDAN: I'm having a hard time deciding\n"
	.string "where I should catch POKEMON next.\p"
	.string "Hey, {PLAYER}, if I see you while I'm out\n"
	.string "catching POKEMON, I can pitch you a\l"
	.string "battle if you'd like.$"

UnknownString_8173A76: @ 8173A76
	.string "It's lined with POKEMON picture books.$"

LittlerootTown_MaysHouse_2F_Text_DespereauxBook::
	.string "The Tale Of Despereaux\p"
	.string "Chapter One\n"
	.string "the last one\p"
	.string "THIS STORY BEGINS within the\n"
	.string "walls of a castle, with the\l"
	.string "birth of a mouse.\p"
	.string "A small mouse. The last mouse\n"
	.string "born to his parents, and the\l"
	.string "only one of his litter to be\l"
	.string "born alive...\p"
	.string "{PLAYER} closes the book carefully.$"
