gBirchSpeech_Welcome:: @ 81C6D78
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to POKEMON LILAC!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKEMON\n"
	.string "PROFESSOR.\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "This is what we call a POKEMON.$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKEMON.\p"
	.string "Every journey has its own color.\n"
	.string "This one begins in lilac.\p"
	.string "Some POKEMON run beside us.\n"
	.string "Some help us work.\l"
	.string "Some sing when words are not enough.\p"
	.string "Today, a special partner is waiting\n"
	.string "for someone with a brave heart.\p"
	.string "To understand bonds like that,\n"
	.string "I study POKEMON every day.\l"
	.string "That's what I do.\p$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "And you are?$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What should I call you?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it's {PLAYER}{KUN}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN}, the one moving\n"
	.string "to my hometown of LITTLEROOT today.\l"
	.string "I get it now!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "All right, are you ready?\p"
	.string "Your very own lilac-colored adventure\n"
	.string "is about to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKEMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKEMON LAB.\p$"
