PlayersHouse_2F_Text_ClockIsStopped:: @ 8172E18
	.string "The clock is stopped...\p"
	.string "Better set it and start it!$"

PlayersHouse_2F_Text_HowDoYouLikeYourRoom:: @ 8172E4C
	.string "MOM: {PLAYER}, how do you like your\n"
	.string "new room?\p"
	.string "Good! Everything's put away neatly!\p"
	.string "They finished moving everything in\n"
	.string "downstairs, too.\p"
	.string "POKEMON movers are so convenient!\p"
	.string "And look, your JIGGLYPUFF doll made\n"
	.string "the trip safely.\p"
	.string "You should make sure everything's\n"
	.string "all there on your desk.$"

UnknownString_8172F31: @ 8172F31
	.string "The bookshelf is lined with books on\n"
	.string "POKEMON and singing contests.\p"
	.string "It's {PLAYER}'s prized collection.$"

UnknownString_8172F85: @ 8172F85
	.string "{PLAYER} booted up the PC.$"

PlayersHouse_2F_Text_Notebook:: @ 8172F9A
	.string "{PLAYER} flipped open the notebook.\p"
	.string "ADVENTURE RULE NO. 1\n"
	.string "Open the MENU with START.\p"
	.string "ADVENTURE RULE NO. 2\n"
	.string "Record your progress with SAVE.\p"
	.string "A lilac bookmark marks a blank page.$"

Common_Text_LookCloserAtMap: @ 817303D
	.string "{PLAYER} took a closer look at the\n"
	.string "HOENN region map.$"

PlayersHouse_2F_Text_ItsAGameCube:: @ 817306C
	.string "It's a Nintendo GameCube.\p"
	.string "A Game Boy Advance is connected to\n"
	.string "serve as the Controller.$"
