Route103_Text_16D57A:: @ 816D57A
	.string "MAY: Let's see... The POKEMON found\n"
	.string "on ROUTE 103 include...$"

Route103_Text_16D5B6:: @ 816D5B6
	.string "Oh, hi, {PLAYER}{KUN}!\p"
	.string "...Oh, I see, my dad gave you a\n"
	.string "POKEMON as a gift.\p"
	.string "Since we're here, let's have a quick\n"
	.string "battle!\p"
	.string "I'll give you a taste of what being a\n"
	.string "TRAINER is like.$"

Route103_Text_16D65B:: @ 816D65B
	.string "Wow! That's great!\n"
	.string "{PLAYER}{KUN}, you're pretty good!$"

Route103_Text_16D688:: @ 816D688
	.string "MAY: I think I know why my dad has an\n"
	.string "eye out for you now.\p"
	.string "I mean, you just got that POKEMON but\n"
	.string "it already likes you.\p"
	.string "You might be able to befriend any\n"
	.string "kind of POKEMON easily.\p"
	.string "Well, it's time to head back to the\n"
	.string "LAB.$"

Route103_Text_16D762:: @ 816D762
	.string "BRENDAN: Okay, so it's this one and\n"
	.string "that one that live on ROUTE 103...$"

Route103_Text_16D7A9:: @ 816D7A9
	.string "Hey, it's {PLAYER}!\p"
	.string "So Dad gave you JIGGLYPUFF after all.\n"
	.string "Nice.\p"
	.string "That means your adventure has really\n"
	.string "started.\p"
	.string "Since we're here, how about a little\n"
	.string "battle?\p"
	.string "Let's see what kind of team you two\n"
	.string "are already becoming!$"

Route103_Text_16D836:: @ 816D836
	.string "Huh, {PLAYER}, you're not too shabby.$"

Route103_Text_16D856:: @ 816D856
	.string "BRENDAN: I think I get it.\n"
	.string "I think I know why Dad had his eye\l"
	.string "out for you now.\p"
	.string "Look, your JIGGLYPUFF already trusts\n"
	.string "you, even though you just met.\p"
	.string "{PLAYER}, I get the feeling that you\n"
	.string "could befriend any POKEMON with ease.\p"
	.string "We should head back to the LAB.\n"
	.string "Dad will want to see this.$"

Route103_Text_16D950:: @ 816D950
	.string "My POKEMON is staggeringly tired...\n"
	.string "I should have brought a POTION...$"

Route103_Text_16D996:: @ 816D996
	.string "If you cross the sea from here,\n"
	.string "it'll be a shortcut to OLDALE TOWN.\p"
	.string "Fufufu, that's useful, isn't it?$"

Route103_Text_16D9FB:: @ 816D9FB
	.string "ROUTE 103\n"
	.string "{0x7A} OLDALE TOWN$"
