PlayersHouse_1F_Text_IsntItNiceInHere:: @ 8172429
	.string "MOM: See, {PLAYER}?\n"
	.string "Isn't it nice in here, too?$"

PlayersHouse_1F_Text_MoversPokemonGoSetClock:: @ 8172453
	.string "The mover's POKEMON did all the work\n"
	.string "of moving us in and cleaning up after.\l"
	.string "This is so convenient!\p"
	.string "{PLAYER}, your room is upstairs.\n"
	.string "Go check it out, dear!\p"
	.string "I unpacked a little birthday surprise\n"
	.string "for you, too.\l"
	.string "Don't forget to set your clock!$"

PlayersHouse_1F_Text_ArentYouInterestedInRoom:: @ 8172531
	.string "MOM: Well, {PLAYER}?\p"
	.string "Aren't you interested in seeing your\n"
	.string "very own room?$"

PlayersHouse_1F_Text_GoSetTheClock:: @ 8172574
	.string "MOM: {PLAYER}.\p"
	.string "Go set the clock in your room, honey.$"

PlayersHouse_1F_Text_OhComeQuickly:: @ 81725A3
	.string "MOM: Oh! {PLAYER}, come quickly!\n"
	.string "The gardening show is starting!$"

PlayersHouse_1F_Text_MaybeDadWillBeOn:: @ 81725C9
	.string "MOM: Look at those flower beds!\n"
	.string "They planted LILACS by the door!$"

PlayersHouse_1F_Text_ItsOverWeMissedHim:: @ 81725FE
	.string "MOM: Oh... It's over.\p"
	.string "Those LILACS were lovely!\n"
	.string "Maybe we should plant some here.$"

PlayersHouse_1F_Text_GoIntroduceYourselfNextDoor:: @ 8172644
	.string "Oh, yes.\n"
	.string "PROF. BIRCH lives right next door.\p"
	.string "You should go over and introduce\n"
	.string "yourself.\p"
	.string "He sounded very excited about today.$"

PlayersHouse_1F_Text_SeeYouHoney:: @ 81726D2
	.string "MOM: See you, honey!$"

PlayersHouse_1F_Text_DidYouMeetProfBirch:: @ 81726E7
	.string "MOM: Did you introduce yourself to\n"
	.string "PROF. BIRCH?$"

PlayersHouse_1F_Text_YouShouldRestABit:: @ 8172717
	.string "MOM: How are you doing, {PLAYER}?\n"
	.string "You look a little tired.\p"
	.string "I think you should rest a bit.$"

PlayersHouse_1F_Text_TakeCareHoney:: @ 817276B
	.string "MOM: Take care, honey!$"

PlayersHouse_1F_Text_GotDadsBadgeHeresSomethingFromMom:: @ 8172782
	.string "MOM: Oh? Did DAD give you that BADGE?\p"
	.string "Then here's something from your MOM!$"

PlayersHouse_1F_Text_DontPushYourselfTooHard:: @ 81727CD
	.string "Don't push yourself too hard, dear.\n"
	.string "You can always come home.\p"
	.string "Go for it, honey!$"

PlayersHouse_1F_Text_Machoke1:: @ 817281D
	.string "Gyao, gyao gyaoh...$"

PlayersHouse_1F_Text_Machoke2:: @ 8172831
	.string "Gwagwah gwah...$"

PlayersHouse_1F_Text_ReportFromPetalburgGym:: @ 8172841
	.string "HOST: ...And that is how you help\n"
	.string "LILACS settle into a new garden.$"

PlayersHouse_1F_Text_TheresAMovieOnTV: @ 817288C
	.string "There is a movie on TV.\p"
	.string "A pink POKEMON is singing on a small\n"
	.string "stage under lilac lights.\p"
	.string "Better get going!$"

UnknownString_81728E3: @ 81728E3
	.string "It's the instruction booklet for the\n"
	.string "RUNNING SHOES.\p"
	.string "Press the B Button to run while\n"
	.string "wearing your RUNNING SHOES.\p"
	.string "Lace up your RUNNING SHOES and hit\n"
	.string "the road running!$"

PlayersHouse_1F_Text_TicketFromBrineyCameForYou:: @ 817298B
	.string "DAD: Hm?\p"
	.string "Hey, it's {PLAYER}!\p"
	.string "It's been a while since I saw you,\n"
	.string "but you look...stronger, somehow.\p"
	.string "That's the impression I get.\n"
	.string "But your old man hasn't given up yet!\p"
	.string "Oh, yes, I have something for you.\n"
	.string "This came to you from someone named\l"
	.string "MR. BRINEY.$"

PlayersHouse_1F_Text_PortsInSlateportLilycove:: @ 8172A7D
	.string "DAD: Hm, a TICKET for a ferry?\p"
	.string "If I recall, there are ferry ports in\n"
	.string "SLATEPORT and LILYCOVE.\p"
	.string "{PLAYER}, if you have ambition as a\n"
	.string "TRAINER, go to the BATTLE TOWER.\p"
	.string "It should teach you that there is\n"
	.string "no end to a TRAINER's chosen path.$"

PlayersHouse_1F_Text_BetterGetBackToGym:: @ 8172B5E
	.string "I'd better get back to PETALBURG GYM.\p"
	.string "MOM, thanks for looking after the house\n"
	.string "while I'm away.$"

PlayersHouse_1F_Text_DadShouldStayLonger:: @ 8172BBC
	.string "MOM: That DAD of yours...\p"
	.string "He comes home for the first time in a\n"
	.string "while, but all he talks about POKEMON.\p"
	.string "He should relax and stay a little longer.$"

UnknownString_8172C50: @ 8172C50
	.string "We bring you a special news bulletin.\p"
	.string "We've received reports of a blue FLYING\n"
	.string "POKEMON in various HOENN locales.\p"
	.string "The identity of this POKEMON has not\n"
	.string "yet been determined.\p"
	.string "We now return you to your regular\n"
	.string "movie presentation.$"

UnknownString_8172D30: @ 8172D30
	.string "We bring you a special news bulletin.\p"
	.string "We've received reports of a red FLYING\n"
	.string "POKEMON in various HOENN locales.\p"
	.string "The identity of this POKEMON has not\n"
	.string "yet been determined.\p"
	.string "We now return you to your regular\n"
	.string "movie presentation.$"

UnknownString_8172E0F: @ 8172E0F
	.string "Gau gau!$"
