UnknownString_8173A9D: @ 8173A9D
	.string "POKEMON SPECIES & HABITATS...\n"
	.string "HUMAN & POKEMON COEXISTENCE...\l"
	.string "POKEMONOLOGY FOR BEGINNERS...\p"
	.string "It's brimming with books written by\n"
	.string "PROF. BIRCH.$"

LittlerootTown_ProfessorBirchsLab_Text_BirchAwayOnFieldwork:: @ 8173B29
	.string "Hunh? PROF. BIRCH?\p"
	.string "The PROF's away on fieldwork.\n"
	.string "Ergo, he isn't here.\p"
	.string "He was carrying a POKE BALL like it was\n"
	.string "a birthday cake, though.\p"
	.string "Oh, let me explain what fieldwork is.\p"
	.string "It is to study things in the natural\n"
	.string "environment, like fields and mountains,\l"
	.string "instead of a laboratory.$"

LittlerootTown_ProfessorBirchsLab_Text_BirchIsntOneForDeskWork:: @ 8173C88
	.string "The PROF isn't one for doing desk work.\n"
	.string "He's the type of person who would\l"
	.string "rather go outside and experience\l"
	.string "things than read about them here.$"

LittlerootTown_ProfessorBirchsLab_Text_BirchEnjoysRivalsHelpToo:: @ 8173D15
	.string "PROF. BIRCH is studying the habitats\n"
	.string "and distribution of POKEMON.\p"
	.string "The PROF enjoys {RIVAL}'s help, too.\n"
	.string "There's a lot of love there.$"

LittlerootTown_ProfessorBirchsLab_Text_LikeYouToHavePokemon:: @ 8173D94
	.string "PROF. BIRCH: So, {PLAYER}{KUN}.\p"
	.string "I have heard so much about you from\n"
	.string "your father.\p"
	.string "I also heard today was a very special\n"
	.string "day for you.\p"
	.string "The way you battled earlier proved\n"
	.string "something I already suspected.\p"
	.string "This JIGGLYPUFF and you have the start\n"
	.string "of a wonderful bond.\p"
	.string "As thanks for rescuing me, and as a\n"
	.string "little birthday welcome to HOENN,\l"
	.string "I'd like you to have that POKEMON.\p"
	.string "{PLAYER} received the {STR_VAR_1}!$"

LittlerootTown_ProfessorBirchsLab_Text_WhyNotGiveNicknameToMon:: @ 8173EF8
	.string "PROF. BIRCH: While you're at it, why not\n"
	.string "give a nickname to that {STR_VAR_1}?$"

LittlerootTown_ProfessorBirchsLab_Text_MightBeGoodIdeaToGoSeeRival:: @ 8173F3D
	.string "PROF. BIRCH: If you work with POKEMON\n"
	.string "and gain experience, I think you'll make\l"
	.string "a darn good TRAINER.\p"
	.string "My kid, {RIVAL}, is out on ROUTE 103\n"
	.string "studying POKEMON.\p"
	.string "{RIVAL} helped me get ready for today,\n"
	.string "so it might not be a bad idea for you\l"
	.string "to go say hello. What do you think?$"

LittlerootTown_ProfessorBirchsLab_Text_GetRivalToTeachYou:: @ 8174015
	.string "PROF. BIRCH: Great!\n"
	.string "{RIVAL} should be happy, too.\p"
	.string "Get {RIVAL} to teach you what it\n"
	.string "means to be a TRAINER.$"

LittlerootTown_ProfessorBirchsLab_Text_DontBeThatWay:: @ 8174075
	.string "PROF. BIRCH: Oh, don't be that way.\n"
	.string "You should go meet my kid.$"

LittlerootTown_ProfessorBirchsLab_Text_BirchRivalRoute103:: @ 81740B4
	.string "PROF. BIRCH: {RIVAL} should be on\n"
	.string "ROUTE 103 somewhere.\p"
	.string "If you or your POKEMON get tired,\n"
	.string "get some rest at home.$"

LittlerootTown_ProfessorBirchsLab_Text_HeardYouBeatRivalTakePokedex:: @ 817411F
	.string "PROF. BIRCH: Oh, hi, {PLAYER}{KUN}!\p"
	.string "I heard you beat {RIVAL} on\n"
	.string "your first try. That's excellent!\p"
	.string "{RIVAL}'s been helping with my research\n"
	.string "for a long time.\p"
	.string "And your JIGGLYPUFF already looks like\n"
	.string "it trusts you.\p"
	.string "Here, {PLAYER}{KUN}, I ordered this for my\n"
	.string "research, but I think you should have\l"
	.string "this POKEDEX.$"

LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex:: @ 817422F
	.string "{PLAYER} received the POKEDEX!$"

LittlerootTown_ProfessorBirchsLab_Text_ExplainPokedex:: @ 8174248
	.string "PROF. BIRCH: The POKEDEX is a high-tech\n"
	.string "tool that automatically makes a record\l"
	.string "of any POKEMON you meet or catch.\p"
	.string "My kid, {RIVAL}, goes everywhere\n"
	.string "with it.\p"
	.string "Whenever my kid catches a rare POKEMON\n"
	.string "and records its data in the POKEDEX,\l"
	.string "why, {RIVAL} looks for me while I'm out\l"
	.string "doing fieldwork, and shows me.$"

LittlerootTown_ProfessorBirchsLab_Text_CountlessPokemonAwait:: @ 817436C
	.string "PROF. BIRCH: Countless POKEMON await\n"
	.string "you!\p"
	.string "Argh, I'm getting the itch to get out\n"
	.string "and do fieldwork again!$"

LittlerootTown_ProfessorBirchsLab_Text_MayGotPokedexTooTakeThese:: @ 81743D4
	.string "MAY: Oh, wow, {PLAYER}{KUN}!\n"
	.string "You got a POKEDEX, too!\p"
	.string "That's great! Just like me!\n"
	.string "I've got something for you, too!$"

LittlerootTown_ProfessorBirchsLab_Text_CatchCutePokemonWithPokeBalls:: @ 817443D
	.string "MAY: It's fun if you can get a lot of\n"
	.string "POKEMON!\p"
	.string "I'm going to look all over the place\n"
	.string "because I want different POKEMON.\p"
	.string "If I find any cute POKEMON, I'll catch\n"
	.string "them with POKE BALLS!$"

LittlerootTown_ProfessorBirchsLab_Text_OhYourBagsFull:: @ 81744F0
	.string "Oh? Your BAG's full.$"

LittlerootTown_ProfessorBirchsLab_Text_MayWhereShouldIGoNext:: @ 8174505
	.string "MAY: I wonder where I should go look\n"
	.string "for POKEMON next?$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanGotPokedexTooTakeThese:: @ 817453C
	.string "BRENDAN: Huh...\n"
	.string "So you got a POKEDEX, too.\p"
	.string "Dad really did have something special\n"
	.string "planned for you.\p"
	.string "Well then, here.\n"
	.string "I'll give you these.$"

LittlerootTown_ProfessorBirchsLab_Text_CatchCoolPokemonWithPokeBalls:: @ 817458C
	.string "BRENDAN: You know it's more fun to\n"
	.string "have a whole bunch of POKEMON.\p"
	.string "I'm going to explore all over the place\n"
	.string "to find different POKEMON.\p"
	.string "If you and JIGGLYPUFF meet any cool\n"
	.string "POKEMON, try these POKE BALLS!$"

LittlerootTown_ProfessorBirchsLab_Text_HeyYourBagsFull:: @ 817465B
	.string "Hey, your BAG's full.$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanWhereShouldIGoNext:: @ 8174671
	.string "BRENDAN: Where should I look for\n"
	.string "POKEMON next...$"

LittlerootTown_ProfessorBirchsLab_Text_SeriousLookingMachine:: @ 81746A2
	.string "It's a serious-looking machine.\n"
	.string "The PROF must use this for research.$"

LittlerootTown_ProfessorBirchsLab_Text_PCUsedForResearch:: @ 81746E7
	.string "It's a PC used for research.\n"
	.string "Better not mess around with it.$"

LittlerootTown_ProfessorBirchsLab_Text_CrammedWithBooksOnPokemon:: @ 8174724
	.string "It's crammed with books on POKEMON.$"

LittlerootTown_ProfessorBirchsLab_Text_BookTooHardToRead:: @ 8174748
	.string "It's a book that's too hard to read.$"
