LittlerootTown_Text_OurNewHomeLetsGoInside:: @ 816A7C9
	.string "MOM: {PLAYER}, we're here, honey!\p"
	.string "It must be tiring riding with our things\n"
	.string "in the moving truck.\p"
	.string "Well, this is LITTLEROOT TOWN.\p"
	.string "How do you like it?\n"
	.string "This is our new home!\p"
	.string "It's quiet, but it has such a sweet\n"
	.string "lilac feeling, don't you think?\p"
	.string "And you get your own room, {PLAYER}!\n"
	.string "Let's go inside.$"

LittlerootTown_Text_WaitPlayer:: @ 816A8EE
	.string "MOM: Wait, {PLAYER}!$"

LittlerootTown_Text_WearTheseRunningShoes:: @ 816A8FD
	.string "MOM: {PLAYER}! {PLAYER}! Did you\n"
	.string "introduce yourself to PROF. BIRCH?\p"
	.string "Oh! What an adorable JIGGLYPUFF!\n"
	.string "You got it from PROF. BIRCH. How nice!\p"
	.string "You two already look like a perfect\n"
	.string "team.\p"
	.string "Here, honey! If you're going out on an\n"
	.string "adventure, wear these RUNNING SHOES.\p"
	.string "They'll put a zip in your step!$"

LittlerootTown_Text_SwitchShoesWithRunningShoes:: @ 816AA32
	.string "{PLAYER} switched shoes with the\n"
	.string "RUNNING SHOES.$"

LittlerootTown_Text_ExplainRunningShoes:: @ 816AA5C
	.string "MOM: {PLAYER}, those shoes came with\n"
	.string "instructions.\p"
	.string "Press the B Button while wearing these\n"
	.string "RUNNING SHOES to run extra-fast!\p"
	.string "Slip on these RUNNING SHOES and race\n"
	.string "in the great outdoors!$"

LittlerootTown_Text_ComeHomeIfAnythingHappens:: @ 816AB10
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "To think that you have your very own\n"
	.string "POKEMON now...\l"
	.string "Your father will be overjoyed.\p"
	.string "And on a day like today, too...\n"
	.string "What a wonderful beginning.\p"
	.string "But please be careful.\n"
	.string "If anything happens, you can come home.\p"
	.string "Go on, go get them, honey!$"

LittlerootTown_Text_CanUsePCToStoreItems:: @ 816AC00
	.string "If you use a PC, you can store items\n"
	.string "and POKEMON.\p"
	.string "The power of science is staggering!$"

LittlerootTown_Text_BirchSpendsDaysInLab:: @ 816AC56
	.string "PROF. BIRCH spends days in his LAB\n"
	.string "studying, then he'll suddenly go out in\l"
	.string "the wild to do more research...\p"
	.string "Today he looked like he was carrying\n"
	.string "something carefully wrapped.$"

LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut:: @ 816ACEB
	.string "If you go in the tall grass at the sides\n"
	.string "of this road, wild POKEMON will appear.$"

LittlerootTown_Text_DangerousIfYouDontHavePokemon:: @ 816AD3C
	.string "It's not safe to go out there if you\n"
	.string "don't have any POKEMON with you.$"

LittlerootTown_Text_CanYouGoSeeWhatsHappening:: @ 816AD82
	.string "I can hear someone shouting down the\n"
	.string "road here.\p"
	.string "What should I do? What should we do?\n"
	.string "Somebody has to go help...$"

LittlerootTown_Text_YouSavedBirch:: @ 816ADF2
	.string "Boy, am I glad you went and rescued\n"
	.string "the PROFESSOR.$"

LittlerootTown_Text_GoodLuckCatchingPokemon:: @ 816AE25
	.string "Are you going to catch POKEMON?\n"
	.string "Good luck!$"

LittlerootTown_Text_TownSign:: @ 816AE50
	.string "LITTLEROOT TOWN\n"
	.string "A town where every journey finds a hue.$"

LittlerootTown_Text_ProfBirchsLab:: @ 816AE87
	.string "PROF. BIRCH'S POKEMON LAB$"

LittlerootTown_Text_PlayersHouse:: @ 816AEA1
	.string "{PLAYER}'s HOUSE$"

LittlerootTown_Text_ProfBirchsHouse:: @ 816AEAC
	.string "PROF. BIRCH'S HOUSE$"
